name: sync-89996462
on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: sync 89996462
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/89996462/Quantumult-X.git"
          source_branch: "main"
          destination_branch: "89996462"
          github_token: ${{ secrets.PAT }}
