name: sync-I-am-R-E
on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: sync I-am-R-E
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/I-am-R-E/Functional-Store-Hub.git"
          source_branch: "master"
          destination_branch: "I-am-R-E"
          github_token: ${{ secrets.PAT }}
